-- 코드를 입력하세요
SELECT FOOD_TYPE
     , REST_ID
     , REST_NAME
     , FAVORITES
FROM REST_INFO AS RI1
WHERE FAVORITES = (SELECT MAX(FAVORITES)
                   FROM REST_INFO AS RI2
                   WHERE RI1.FOOD_TYPE = RI2.FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;